from tkinter import *

app = Tk() 
app.config(bg="#9ea6ad")

label = Label(text="hello" ,bg="red",width=12)
label.grid(row=0, column=0,pady=2)
label = Label(text="hello",bg="red",width=12)
label.grid(row=1, column=0,pady=2)
label = Label(text="hello",bg="red",width=12)
label.grid(row=2, column=0,pady=2)
label = Label(text="hello",bg="red",width=12)
label.grid(row=3, column=0,pady=2)
label = Label(text="hello",bg="red",width=12)
label.grid(row=4, column=0, pady=2)

label = Label(text="hello" ,bg="red",width=12)
label.grid(row=0, column=1,pady=2,padx=2)
label = Label(text="hello",bg="red",width=12)
label.grid(row=1, column=1,pady=2,padx=2)
label = Label(text="hello",bg="red",width=12)
label.grid(row=2, column=1,pady=2,padx=2)
label = Label(text="hello",bg="red",width=12)
label.grid(row=3, column=1,pady=2,padx=2)
label = Label(text="hello",bg="red",width=12)
label.grid(row=4, column=1, pady=2,padx=2)

label = Label(text="hello" ,bg="red",width=12)
label.grid(row=0, column=2,pady=2,padx=2)
label = Label(text="hello",bg="red",width=12)
label.grid(row=1, column=2,pady=2,padx=2)
label = Label(text="hello",bg="red",width=12)
label.grid(row=2, column=2,pady=2,padx=2)
label = Label(text="hello",bg="red",width=12)
label.grid(row=3, column=2,pady=2,padx=2)
label = Label(text="hello",bg="red",width=12)
label.grid(row=4, column=2, pady=2,padx=2)

label = Label(text="hello" ,bg="red",width=12)
label.grid(row=0, column=3,pady=2,padx=2)
label = Label(text="hello",bg="red",width=12)
label.grid(row=1, column=3,pady=2,padx=2)
label = Label(text="hello",bg="red",width=12)
label.grid(row=2, column=3,pady=2,padx=2)
label = Label(text="hello",bg="red",width=12)
label.grid(row=3, column=3,pady=2,padx=2)
label = Label(text="hello",bg="red",width=12)
label.grid(row=4, column=3, pady=2,padx=2)
button = Button(text="Fetch",width=12)
button.grid()



app.mainloop()
